version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: splitmate-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: splitmate
      POSTGRES_USER: splitmate_user
      POSTGRES_PASSWORD: splitmate_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./backend/src/database/postgres-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U splitmate_user -d splitmate"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - splitmate-network-postgres

  # Backend API (PostgreSQL Development)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.postgres
    container_name: splitmate-backend-postgres-dev
    restart: unless-stopped
    env_file:
      - ./backend/.env.local
    environment:
      DATABASE_URL: postgresql://splitmate_user:splitmate_password@postgres:5432/splitmate
      NODE_ENV: development
      PORT: 3001
      # Basic URLs for development
      BACKEND_URL: http://localhost:3001
      FRONTEND_URL: http://localhost:5173
      SESSION_SECRET: your-development-session-secret
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app/backend
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - splitmate-network-postgres

  # Frontend (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: splitmate-frontend-postgres-dev
    restart: unless-stopped
    environment:
      VITE_BACKEND_URL: http://localhost:3001
      VITE_FRONTEND_URL: http://localhost:5173
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - splitmate-network-postgres

volumes:
  postgres_data_dev:

networks:
  splitmate-network-postgres:
    driver: bridge
