[build]
  base = "frontend"
  publish = "dist"
  command = "npm ci --include=dev && npm run build"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--include=dev"

# SPA用のリダイレクト設定
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# セキュリティヘッダー
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# フロントエンド用環境変数の設定例
[context.production]
  environment = { NODE_ENV = "production" }
  
[context.deploy-preview]
  environment = { NODE_ENV = "development" }
  
[context.branch-deploy]
  environment = { NODE_ENV = "development" } 
