services:
  - type: web
    name: splitmate-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile.prod
    dockerContext: .
    plan: free
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
    healthCheckPath: /health

databases:
  - name: splitmate-postgres
    databaseName: splitmate
    user: splitmate_user
    plan: free
# Render用のポート設定
# Renderは自動的にPORTを設定するため、追加設定不要
