services:
  - type: web
    name: splitmate-backend
    runtime: node
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm start
    plan: free
    rootDir: backend
    env:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.17.0
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: splitmate-postgres
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://splitmate-frontend.netlify.app
      - key: BACKEND_URL
        value: https://splitmate-backend.onrender.com
    healthCheckPath: /health

databases:
  - name: splitmate-postgres
    databaseName: splitmate
    user: splitmate_user
    plan: free
# Render用のポート設定
# Renderは自動的にPORTを設定するため、追加設定不要
